AD-6773 SoftwareStatement version changed to string
OpenBankingUK/directory-api-specs pull request #31
Opened 2023-01-18 10:49 UTC by MichalZawilski

2023-01-20 09:59 UTC, emilia-markowska approved these changes

2023-02-07 11:05 UTC, fosterOpenBanking requested changes
We need to standardise (and correct)  the description of this field please.  If we go for a description that aligns with what is stated in the RFC, that would be better. It's meant to denote a version of the client software and not the software statement.

2023-02-08 08:03 UTC, MichalZawilski commented
@fosterOpenBanking 
Added requested changes. Please check if it's correct now.

2023-02-09 12:15 UTC, fosterOpenBanking commented
Approved.

2023-02-15 13:33 UTC, merged